# Generated by Django 2.1.5 on 2019-02-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='decription',
            new_name='description',
        ),
    ]
